# Generated by Django 5.2 on 2025-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('librarian', 'Librarian')], default='student', max_length=20, null=True),
        ),
    ]
